name: Update Puzzles Twice Daily

on:
  schedule:
    - cron: '0 5 * * *'
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  update-puzzles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    - name: Run update
      run: node update-puzzles.js
