name: Update Puzzles Twice Daily

on:
  schedule:
    # Run at 5:00 AM UTC (12:00 AM EST) and 5:00 PM UTC (12:00 PM EST)
    - cron: '0 5 * * *'
    - cron: '0 17 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-puzzles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
    - name: Run puzzle update
      run: |
        node update-puzzles.js
        
    - name: Check if changes were made
      id: verify
      run: |
        if [[ -f "last-update.json" ]]; then
          echo "Update completed successfully"
          cat last-update.json
        else
          echo "No update file found"
          exit 1 